# These are supported funding model platforms
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files
patreon: cuzi
ko_fi: cuzicvzi
liberapay: cuzi
custom:
    - https://buymeacoff.ee/cuzi
    - https://flattr.com/@cuzi/github/cvzi
    - https://blockchain.info/address/3KDs3RjvsKzbFQ8XoHkGqZxQtSxn2WYbn1
