name: buildTest

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test npm run build
      run: |
        npm install
        npm run build
        npm run build:release
        npm run build:singledomain
        npm run testserve
